import type { InvoiceTemplatePage } from "@/lib/invoice-template-pages";

const updatedAt = "2026-07-05";

export const INVOICE_TEMPLATE_BATCH_TWO: InvoiceTemplatePage[] = [
  {
    slug: "hvac-technician-invoice-template",
    profession: "HVAC Technician",
    category: "Home services",
    primaryKeyword: "HVAC invoice template",
    title: "Free HVAC Invoice Template | AC Service GST Bill",
    description: "Create an HVAC invoice for AC inspection, repair labour, refrigerant, parts and maintenance. Add GST and make a professional service PDF online.",
    h1: "HVAC Invoice Template for AC Service and Repairs",
    intro: "Prepare an HVAC bill that distinguishes diagnosis, technician labour, refrigerant, replacement parts and scheduled maintenance. The format works for residential AC service, commercial cooling systems and annual maintenance visits.",
    billingModel: "Visit + technician labour + parts",
    sampleBusiness: "CoolCare HVAC Services",
    sampleCustomer: "Silver Oak Business Centre",
    sampleItems: [
      { name: "AC inspection", detail: "Cooling and electrical diagnosis", amount: 800 },
      { name: "Service labour", detail: "Indoor and outdoor unit cleaning", amount: 1500 },
      { name: "Refrigerant top-up", detail: "Measured refill", amount: 2200 },
    ],
    requiredFields: [
      { title: "Equipment details", body: "Record the AC type, capacity, brand or asset number so the bill identifies the serviced unit." },
      { title: "Diagnosis and work", body: "Describe the reported fault, inspection result and completed repair or maintenance." },
      { title: "Parts and refrigerant", body: "Show replaced components and refrigerant charges separately from technician labour." },
    ],
    tips: ["Reference the AMC or service-ticket number when one exists.", "Note measured refrigerant quantity or component model where practical.", "State the workmanship and part warranty separately."],
    mistakes: [
      { title: "No equipment reference", body: "Commercial customers may have many units; identify the exact asset that was serviced." },
      { title: "Generic gas charge", body: "Describe the refrigerant service and agreed quantity or basis instead of an unexplained lump sum." },
    ],
    faqs: [
      ["What should an HVAC invoice include?", "Include customer and technician details, service address, equipment, diagnosis, labour, parts, refrigerant, tax, total and payment terms."],
      ["Can AC inspection be charged separately?", "Yes. Add diagnosis or a call-out visit as its own line when it has an agreed fee."],
      ["How do I invoice an AMC visit?", "Reference the annual maintenance contract and service period, then list included work and separately billable parts."],
      ["Should refrigerant appear separately?", "Yes. A separate line makes the material charge easier for the customer to understand."],
      ["Can the HVAC invoice include GST?", "Yes, when applicable. Use the correct tax details and confirm the treatment for your service and supplied parts."],
    ],
    relatedSlugs: ["electrician-invoice-template", "plumber-invoice-template", "contractor-invoice-template"],
    updatedAt,
  },
  {
    slug: "painter-invoice-template",
    profession: "Painter",
    category: "Home services",
    primaryKeyword: "painter invoice template",
    title: "Free Painter Invoice Template | Paint Bill Format",
    description: "Create a painting invoice for measured area, surface preparation, labour, paint and materials. Add project stages, GST and make a PDF bill online.",
    h1: "Painter Invoice Template for Labour and Materials",
    intro: "Invoice residential or commercial painting with a clear measurement basis and separate preparation, coats, labour and material charges. It supports room-wise work, fixed projects and milestone billing.",
    billingModel: "Measured area + preparation + materials",
    sampleBusiness: "TrueTone Painting Works",
    sampleCustomer: "Maple Residency Owners Association",
    sampleItems: [
      { name: "Wall preparation", detail: "Putty and sanding · 850 sq ft", amount: 12750 },
      { name: "Interior painting labour", detail: "Two coats · 850 sq ft", amount: 17000 },
      { name: "Premium emulsion paint", detail: "Approved colour and quantity", amount: 14500 },
    ],
    requiredFields: [
      { title: "Measured area", body: "Show square feet, rooms or another agreed measurement used to calculate the job." },
      { title: "Surface preparation", body: "List scraping, putty, primer, sanding or repair separately when included." },
      { title: "Paint specification", body: "Record brand, product type, colour or number of coats relevant to the approved estimate." },
    ],
    tips: ["Reference the approved colour schedule or estimate.", "Separate labour-only work from paint supplied by you.", "Show previous advances when billing the final project stage."],
    mistakes: [
      { title: "Missing area or room scope", body: "A total without measurements makes it difficult to match the invoice with the estimate." },
      { title: "No preparation detail", body: "Preparation often explains a large part of labour, so list it clearly." },
    ],
    faqs: [
      ["What belongs on a painter invoice?", "Include project address, measured scope, preparation, labour, paint and supplies, tax, advances, total and due date."],
      ["Can painting be billed per square foot?", "Yes. Enter square feet as the quantity and the agreed rate for each type of work."],
      ["Should paint and labour be separate?", "Separate them when materials are supplied by the painter or when the agreement prices them independently."],
      ["How do I show a painting advance?", "Show the full stage or project amount and deduct the advance already received."],
      ["Can I use this for commercial painting?", "Yes. Add work-order references, site details, measured quantities and the customer's required tax information."],
    ],
    relatedSlugs: ["carpenter-invoice-template", "contractor-invoice-template", "cleaning-service-invoice-template"],
    updatedAt,
  },
  {
    slug: "cleaning-service-invoice-template",
    profession: "Cleaning Service",
    category: "Home services",
    primaryKeyword: "cleaning service invoice template",
    title: "Free Cleaning Service Invoice Template | PDF Bill",
    description: "Create a cleaning invoice for visits, hours, deep cleaning, supplies and recurring contracts. Add service location, GST and make a professional PDF online.",
    h1: "Cleaning Service Invoice Template for Visits and Contracts",
    intro: "Create a cleaning bill for a one-time visit, deep clean, office contract or recurring housekeeping service. Record the service date, property, staff hours and extra treatments so the customer can verify the work.",
    billingModel: "Visit, hourly or recurring contract",
    sampleBusiness: "BrightNest Cleaning Co.",
    sampleCustomer: "Aster Coworking Spaces",
    sampleItems: [
      { name: "Office deep cleaning", detail: "2,500 sq ft service area", amount: 7500 },
      { name: "Cleaning staff", detail: "Three staff × four hours", amount: 3600 },
      { name: "Carpet treatment", detail: "Meeting room and reception", amount: 2200 },
    ],
    requiredFields: [
      { title: "Service date and property", body: "Identify when and where the cleaning was completed." },
      { title: "Scope and frequency", body: "State one-time, weekly or monthly service and list the included areas or tasks." },
      { title: "Staff or measured basis", body: "Use staff hours, visits, square feet or the agreed fixed-service price." },
    ],
    tips: ["Separate add-ons such as carpet, window or sanitisation work.", "Reference the service checklist for recurring commercial work.", "State whether cleaning supplies are included in the rate."],
    mistakes: [
      { title: "Unclear service period", body: "Monthly clients need the exact billing period or visit dates on each invoice." },
      { title: "Bundled add-ons", body: "Show special treatments separately so the customer can match them to approval." },
    ],
    faqs: [
      ["What should a cleaning invoice include?", "Include provider and customer details, property, service dates, scope, hours or visits, add-ons, supplies, tax and total."],
      ["How do I invoice recurring cleaning?", "State the billing month, frequency and covered locations, then list work outside the contract separately."],
      ["Can cleaning be billed hourly?", "Yes. Show staff count or total hours and the agreed hourly rate."],
      ["Should supplies be a separate charge?", "Separate supplies when they are not included in the service rate or were specially approved."],
      ["Can I make a GST cleaning invoice?", "Yes. Add the applicable supplier, customer and tax information for the transaction."],
    ],
    relatedSlugs: ["painter-invoice-template", "salon-invoice-template", "contractor-invoice-template"],
    updatedAt,
  },
  {
    slug: "mobile-repair-invoice-template",
    profession: "Mobile Repair Shop",
    category: "Repair services",
    primaryKeyword: "mobile bill format",
    title: "Mobile Bill Format | Mobile Repair Invoice Template",
    description: "Create a mobile repair invoice for diagnosis, labour, screens, batteries and spare parts. Record device details, warranty, GST and make a PDF bill online.",
    h1: "Mobile Bill Format for Repair Parts and Service",
    intro: "Use this mobile bill format for phone repair work. It identifies the device, reported fault, completed work and replacement part, making warranty follow-up easier and separating technician labour from component cost.",
    billingModel: "Diagnosis + repair labour + spare parts",
    sampleBusiness: "QuickFix Mobile Care",
    sampleCustomer: "Ritika Verma",
    sampleItems: [
      { name: "Device diagnosis", detail: "Power and charging inspection", amount: 300 },
      { name: "Charging-port replacement", detail: "Technician labour", amount: 700 },
      { name: "Charging flex assembly", detail: "Compatible replacement part", amount: 1200 },
    ],
    requiredFields: [
      { title: "Device identification", body: "Record the brand, model and partial serial or IMEI reference without exposing unnecessary personal data." },
      { title: "Fault and repair", body: "Describe the customer's reported issue and the repair actually completed." },
      { title: "Part and warranty", body: "Identify the replacement component and clearly state its warranty period or exclusions." },
    ],
    tips: ["Avoid printing a full IMEI when a masked reference is sufficient.", "State whether the replacement is original, OEM-grade or compatible.", "Record device delivery and payment status."],
    mistakes: [
      { title: "No device model", body: "A repair bill without device identification is difficult to use for warranty claims." },
      { title: "Unclear part quality", body: "Describe the agreed replacement type instead of using only the word spare." },
    ],
    faqs: [
      ["What should a mobile repair invoice include?", "Include shop and customer details, device model, masked identifier, fault, labour, parts, warranty, tax and amount paid or due."],
      ["Should the full IMEI be printed?", "Use only the device reference needed for records and protect customer data. A masked IMEI may be sufficient."],
      ["How do I show a repair warranty?", "State the duration, covered part or workmanship and important exclusions in clear language."],
      ["Can diagnosis be charged separately?", "Yes. Add a diagnosis fee and show whether it is adjusted against the completed repair."],
      ["Can this invoice include GST?", "Yes, when applicable to the service and supplied part. Add the required tax details."],
    ],
    relatedSlugs: ["computer-repair-invoice-template", "electrician-invoice-template", "freelancer-invoice-template"],
    updatedAt: "2026-08-08",
  },
  {
    slug: "computer-repair-invoice-template",
    profession: "Computer Repair Service",
    category: "Repair services",
    primaryKeyword: "computer repair invoice template",
    title: "Free Computer Repair Invoice Template | Service Bill",
    description: "Create a computer repair invoice for diagnosis, support labour, hardware, software and data services. Add device and warranty details, GST and PDF billing.",
    h1: "Computer Repair Invoice Template for IT Service",
    intro: "Invoice laptop and desktop repairs with a clear device reference, diagnosis, technician work and installed hardware or software. The format supports walk-in repairs, onsite support and business maintenance calls.",
    billingModel: "Diagnosis + support time + hardware",
    sampleBusiness: "ByteCare Computer Services",
    sampleCustomer: "Cedar Legal Associates",
    sampleItems: [
      { name: "Laptop diagnosis", detail: "Hardware and operating-system check", amount: 600 },
      { name: "SSD installation labour", detail: "Migration and configuration", amount: 1400 },
      { name: "500 GB SSD", detail: "Replacement storage drive", amount: 3200 },
    ],
    requiredFields: [
      { title: "Device and ticket", body: "Add the laptop or desktop model and service-ticket reference used at intake." },
      { title: "Work performed", body: "Describe diagnosis, repair, configuration, migration or support time." },
      { title: "Hardware and licence", body: "List installed parts and legitimate software licences separately with warranty details." },
    ],
    tips: ["Use a masked serial number when full identification is unnecessary.", "Document customer approval for data migration or recovery.", "Separate remote-support time from onsite travel or call-out fees."],
    mistakes: [
      { title: "Vague technical service", body: "Record the actual repair or configuration so business customers can approve the charge." },
      { title: "No data-service note", body: "Migration or recovery work should state the agreed scope without promising recoverability." },
    ],
    faqs: [
      ["What goes on a computer repair invoice?", "Include device and ticket details, diagnosis, technician labour, parts, software, data services, warranty, tax and total."],
      ["Can remote support be billed hourly?", "Yes. Show the support duration, activity and agreed hourly rate."],
      ["How should replacement hardware appear?", "List the part description, capacity or model, quantity, price and warranty separately."],
      ["Can data recovery be guaranteed?", "No. Invoice only the agreed attempt or completed service and avoid unsupported recovery guarantees."],
      ["Can I use this for business IT support?", "Yes. Add the company, asset, ticket, service period and purchase-order reference where required."],
    ],
    relatedSlugs: ["mobile-repair-invoice-template", "web-developer-invoice-template", "consultant-invoice-template"],
    updatedAt,
  },
  {
    slug: "web-designer-invoice-template",
    profession: "Web Designer",
    category: "Creative and digital services",
    primaryKeyword: "web designer invoice template",
    title: "Free Web Designer Invoice Template | Project PDF",
    description: "Create a web design invoice for discovery, UI pages, responsive layouts, revisions and retainers. Add project milestones, tax and make a client PDF online.",
    h1: "Web Designer Invoice Template for Website Projects",
    intro: "Bill website design work by milestone, page set, sprint or retainer. Connect each fee to approved discovery, wireframes, interface designs, responsive states and revision rounds.",
    billingModel: "Milestone + deliverables + revisions",
    sampleBusiness: "PixelNorth Design Studio",
    sampleCustomer: "Harvest Foods Private Limited",
    sampleItems: [
      { name: "UX discovery", detail: "Brief, sitemap and wireframes", amount: 18000 },
      { name: "Website UI design", detail: "Eight responsive page designs", amount: 48000 },
      { name: "Design revisions", detail: "Two approved revision rounds", amount: 8000 },
    ],
    requiredFields: [
      { title: "Project and milestone", body: "Name the website and approved phase covered by the invoice." },
      { title: "Design deliverables", body: "List pages, templates, breakpoints, files or prototypes delivered." },
      { title: "Revisions and extras", body: "Separate included rounds from additional changes or rush work." },
    ],
    tips: ["Reference the signed proposal or statement of work.", "Invoice deposits and milestones according to the agreed schedule.", "Distinguish design work from development or third-party asset costs."],
    mistakes: [
      { title: "No milestone reference", body: "The client may not know whether the invoice covers discovery, design or final handoff." },
      { title: "Unlimited revision wording", body: "List the included rounds and separately approved additional work." },
    ],
    faqs: [
      ["What should a web designer invoice include?", "Include client and designer details, project, milestone, pages or deliverables, revisions, tax, total and payment deadline."],
      ["How do web designers invoice a deposit?", "Show the project or milestone value and clearly label the upfront deposit amount."],
      ["Can I invoice by page?", "Yes. Use page or template count as the quantity when that matches the approved proposal."],
      ["Should development be separate?", "Separate design and development when they have different scopes, providers or approval stages."],
      ["How do I bill extra revisions?", "Reference the change approval and list the additional hours or fixed revision fee separately."],
    ],
    relatedSlugs: ["web-developer-invoice-template", "freelancer-invoice-template", "digital-marketing-agency-invoice-template"],
    updatedAt,
  },
  {
    slug: "web-developer-invoice-template",
    profession: "Web Developer",
    category: "Creative and digital services",
    primaryKeyword: "web developer invoice template",
    title: "Free Web Developer Invoice Template | Project Bill",
    description: "Create a web developer invoice for features, sprints, integrations, hosting and maintenance. Add project milestones, hours, tax and make a PDF online.",
    h1: "Web Developer Invoice Template for Builds and Support",
    intro: "Invoice development by sprint, feature, milestone or support period. A clear technical description helps clients connect charges to deployed functionality without filling the invoice with unnecessary implementation detail.",
    billingModel: "Sprint, feature, milestone or hourly",
    sampleBusiness: "LaunchStack Web Development",
    sampleCustomer: "Nimble Commerce India",
    sampleItems: [
      { name: "Frontend development", detail: "Responsive product and checkout pages", amount: 42000 },
      { name: "Payment integration", detail: "Gateway setup and testing", amount: 16000 },
      { name: "Maintenance retainer", detail: "July 2026 support", amount: 12000 },
    ],
    requiredFields: [
      { title: "Project or repository reference", body: "Name the website, sprint or work order without exposing private credentials." },
      { title: "Completed functionality", body: "Describe deployed features, integrations, fixes or support outcomes." },
      { title: "Service period or hours", body: "State the sprint dates, maintenance month or approved billable hours." },
    ],
    tips: ["Reference acceptance or deployment milestones.", "Separate hosting and third-party licences from development fees.", "List support outside the maintenance scope as additional work."],
    mistakes: [
      { title: "Overly vague development line", body: "Use client-readable feature descriptions so the invoice can be approved without reading a commit history." },
      { title: "Mixing pass-through costs", body: "Show domains, hosting and licences separately from professional fees." },
    ],
    faqs: [
      ["What belongs on a web developer invoice?", "Include the project, period or milestone, completed features, hours or fixed fees, third-party costs, tax, total and due date."],
      ["Can developers invoice by sprint?", "Yes. Name the sprint dates and accepted scope, then list additional work separately."],
      ["How do I invoice maintenance?", "State the support month, included scope and any approved work outside the retainer."],
      ["Should hosting be a separate item?", "Yes. Separate pass-through hosting, domain and licence costs from development labour."],
      ["Can hourly work be included?", "Yes. Show total hours, rate and a concise description or attach an approved time summary."],
    ],
    relatedSlugs: ["web-designer-invoice-template", "computer-repair-invoice-template", "freelancer-invoice-template"],
    updatedAt,
  },
  {
    slug: "content-writer-invoice-template",
    profession: "Content Writer",
    category: "Creative and digital services",
    primaryKeyword: "content writer invoice template",
    title: "Free Content Writer Invoice Template | Client PDF",
    description: "Create a content writer invoice for articles, words, pages, editing, research and retainers. Add deliverables, tax and payment terms, then make a PDF online.",
    h1: "Content Writer Invoice Template for Articles and Retainers",
    intro: "Create a writing invoice that names the delivered articles, pages, word count or retainer period. Clear deliverables help editors and marketing teams match the bill with accepted content.",
    billingModel: "Per article, word, page or retainer",
    sampleBusiness: "ClearWord Content Studio",
    sampleCustomer: "BrightPath Learning",
    sampleItems: [
      { name: "SEO blog articles", detail: "Four articles · 1,500 words each", amount: 24000 },
      { name: "Content research", detail: "Sources and expert inputs", amount: 5000 },
      { name: "Editorial revisions", detail: "One additional revision round", amount: 2500 },
    ],
    requiredFields: [
      { title: "Content period or project", body: "Name the campaign, website or month covered by the invoice." },
      { title: "Deliverables and quantity", body: "List articles, pages, scripts or word counts using the agreed pricing basis." },
      { title: "Research and revisions", body: "Show separately approved research, interviews or additional editing rounds." },
    ],
    tips: ["Use the client's content or purchase-order reference.", "State the retainer month on recurring invoices.", "Keep platform fees or subcontracted editing separate when billed to the client."],
    mistakes: [
      { title: "Generic writing services", body: "Article names, counts or campaign references make approval much easier." },
      { title: "No retainer period", body: "Recurring clients need to know exactly which month or delivery cycle was billed." },
    ],
    faqs: [
      ["What should a content writer invoice include?", "Include writer and client details, project or month, articles or word count, rate, research, revisions, tax, total and due date."],
      ["Can writers invoice per word?", "Yes. Show word count as the quantity and the agreed per-word rate."],
      ["How do I invoice a content retainer?", "State the month, included deliverables and any additional work outside the retainer."],
      ["Can research be charged separately?", "Yes, when research, interviews or source work was separately agreed."],
      ["Should article titles appear?", "Titles or content references help the client match the invoice to delivered and accepted work."],
    ],
    relatedSlugs: ["freelancer-invoice-template", "web-designer-invoice-template", "digital-marketing-agency-invoice-template"],
    updatedAt,
  },
  {
    slug: "digital-marketing-agency-invoice-template",
    profession: "Digital Marketing Agency",
    category: "Creative and digital services",
    primaryKeyword: "digital marketing agency invoice template",
    title: "Free Digital Marketing Invoice Template | Agency Bill",
    description: "Create a marketing agency invoice for retainers, campaigns, ad management, creative work and pass-through spend. Add GST and make a client PDF online.",
    h1: "Digital Marketing Agency Invoice Template for Campaigns",
    intro: "Create an agency invoice that separates professional fees from media spend, production and third-party tools. It works for monthly retainers, project campaigns and performance-marketing management.",
    billingModel: "Monthly retainer + campaigns + media costs",
    sampleBusiness: "GrowthCurrent Digital",
    sampleCustomer: "UrbanTrail Apparel",
    sampleItems: [
      { name: "Monthly marketing retainer", detail: "Strategy, reporting and account management", amount: 45000 },
      { name: "Paid-media management", detail: "Search and social campaigns", amount: 25000 },
      { name: "Campaign creative production", detail: "Eight static ad variations", amount: 16000 },
    ],
    requiredFields: [
      { title: "Campaign or billing month", body: "Name the period, brand or campaign covered by the invoice." },
      { title: "Agency deliverables", body: "Separate strategy, management, creative production, reporting and other agreed services." },
      { title: "Media and pass-through costs", body: "Keep ad spend and third-party costs distinct from agency professional fees." },
    ],
    tips: ["Reference the retainer agreement or campaign purchase order.", "Do not present platform ad spend as agency revenue when it is paid directly by the client.", "List approved out-of-scope production separately."],
    mistakes: [
      { title: "Mixing media and fees", body: "Clients need a clear split between agency compensation and third-party advertising cost." },
      { title: "Missing campaign period", body: "Always identify the month or campaign associated with recurring charges." },
    ],
    faqs: [
      ["What goes on a marketing agency invoice?", "Include the billing month or campaign, services, deliverables, management fees, approved production, media costs, tax, total and payment terms."],
      ["Should ad spend be separate?", "Yes. Clearly separate media spend or reimbursements from agency professional fees."],
      ["How do I invoice a monthly retainer?", "Name the service month and agreed scope, then list project or out-of-scope work separately."],
      ["Can creative production be itemised?", "Yes. List the approved asset type, quantity or production package."],
      ["Can this format include GST?", "Yes. Add the applicable agency and client tax details and rates for the transaction."],
    ],
    relatedSlugs: ["web-designer-invoice-template", "content-writer-invoice-template", "consultant-invoice-template"],
    updatedAt,
  },
  {
    slug: "chartered-accountant-invoice-template",
    profession: "Chartered Accountant",
    category: "Professional services",
    primaryKeyword: "chartered accountant invoice template",
    title: "Free CA Bill Format | Chartered Accountant Invoice",
    description: "Create a CA bill format or chartered accountant invoice for compliance, returns, audit, advisory and GST professional fees. Make a PDF online.",
    h1: "CA Bill Format for Chartered Accountant Fees",
    intro: "Create a chartered accountant invoice or CA bill format for accounting, compliance, GST return support, audit work and advisory retainers. Separating recurring compliance from project work helps clients route the bill for approval.",
    billingModel: "Engagement, filing, advisory or retainer",
    sampleBusiness: "Mehta Rao & Associates",
    sampleCustomer: "BluePeak Manufacturing Private Limited",
    sampleItems: [
      { name: "Monthly compliance retainer", detail: "June 2026 accounting support", amount: 18000 },
      { name: "GST return assistance", detail: "Monthly return working and review", amount: 6000 },
      { name: "Management reporting", detail: "Quarterly financial summary", amount: 12000 },
    ],
    requiredFields: [
      { title: "Engagement and client entity", body: "Identify the legal entity and agreed engagement, work order or retainer." },
      { title: "Service and period", body: "Name the filing, review, advisory deliverable or month covered." },
      { title: "Professional fee and expenses", body: "Separate fees from approved filing charges, travel or other reimbursements." },
    ],
    tips: ["Use the client's exact legal and GST-registered name.", "Reference the engagement letter or purchase order.", "Avoid putting confidential financial details in the invoice description.", "Use clear CA bill format lines such as GST return filing, accounting retainer, audit support or advisory fee."],
    mistakes: [
      { title: "Unclear entity", body: "Groups may have several companies, so identify the billed legal entity precisely." },
      { title: "Over-disclosing client data", body: "Describe the professional service without exposing confidential figures or filing credentials." },
    ],
    faqs: [
      ["What should a CA invoice include?", "Include firm and client entity details, engagement, service period, professional fees, approved expenses, tax, total and payment instructions."],
      ["How do I invoice a compliance retainer?", "State the month or quarter and the services covered by the agreed retainer."],
      ["Can filing fees be separate?", "Yes. Distinguish professional fees from government charges or other approved reimbursements."],
      ["Should confidential figures appear?", "Usually no. Use a sufficient engagement or service description without exposing private financial information."],
      ["Can GST be added to professional fees?", "Yes, where applicable. Use the correct firm, client and tax details for the supply."],
      ["Can this be used as a CA bill format?", "Yes. Use it for chartered accountant professional fees, GST return work, audit assistance, accounting retainers and advisory billing."],
    ],
    relatedSlugs: ["consultant-invoice-template", "freelancer-invoice-template", "digital-marketing-agency-invoice-template"],
    searchIntents: ["CA bill format", "chartered accountant invoice format", "CA invoice format", "professional fees bill format", "GST return filing bill"],
    updatedAt,
  },
];
