import type { InvoiceTemplatePage } from "@/lib/invoice-template-pages";

const updatedAt = "2026-07-11";

type TemplateSeed = {
  slug: string;
  profession: string;
  category: string;
  primaryKeyword: string;
  title: string;
  h1: string;
  description?: string;
  intro?: string;
  billingModel: string;
  sampleBusiness: string;
  sampleCustomer: string;
  sampleItems: Array<{ name: string; detail: string; amount: number }>;
  required: [string, string, string];
  tips: string[];
  relatedSlugs: string[];
  searchIntents?: string[];
  faqs?: Array<[string, string]>;
  updatedAt?: string;
};

function makeTemplate(seed: TemplateSeed): InvoiceTemplatePage {
  const professionLower = seed.profession.toLowerCase();

  return {
    slug: seed.slug,
    profession: seed.profession,
    category: seed.category,
    primaryKeyword: seed.primaryKeyword,
    title: seed.title,
    description: seed.description ?? `Create a ${professionLower} invoice with itemised services, charges, GST-ready fields and payment terms. Use this free bill format and make a PDF invoice online.`,
    h1: seed.h1,
    intro: seed.intro ?? `Use this ${professionLower} invoice format to turn real work into a clear, professional bill. It includes practical line items, customer-ready descriptions and GST-ready fields so the customer can understand what was delivered and what they need to pay.`,
    billingModel: seed.billingModel,
    sampleBusiness: seed.sampleBusiness,
    sampleCustomer: seed.sampleCustomer,
    sampleItems: seed.sampleItems,
    requiredFields: [
      { title: "Service or job details", body: seed.required[0] },
      { title: "Quantity and charge basis", body: seed.required[1] },
      { title: "Tax and payment terms", body: seed.required[2] },
    ],
    tips: seed.tips,
    mistakes: [
      { title: "Using a generic service line", body: `Avoid writing only ${professionLower} services. Add enough detail for the customer to match the invoice with the actual work.` },
      { title: "Missing approval context", body: "Include dates, location, order reference, package or milestone details when they affect payment approval." },
    ],
    faqs: seed.faqs ?? [
      [`What should a ${professionLower} invoice include?`, `Include business and customer details, invoice number, date, service description, quantities, rate, taxes, total amount and payment instructions.`],
      [`Can I use this as a ${professionLower} bill format?`, "Yes. The page is structured as a practical bill format with sample line items that you can recreate in InvoiceWala."],
      ["Can I add GST details?", "Yes. Add GSTIN, place of supply, HSN/SAC, tax rate and the correct tax split when they apply to your transaction."],
      ["Can I download the invoice as PDF?", "You can create the invoice in InvoiceWala, preview it and download or save the PDF after signing in."],
      ["Should I customise the sample items?", "Yes. Replace all sample names, descriptions, dates and amounts with your actual customer and job details before sending the invoice."],
    ],
    relatedSlugs: seed.relatedSlugs,
    searchIntents: seed.searchIntents,
    updatedAt: seed.updatedAt ?? updatedAt,
  };
}

export const INVOICE_TEMPLATE_BATCH_THREE: InvoiceTemplatePage[] = [
  makeTemplate({
    slug: "mechanic-invoice-template",
    profession: "Mechanic",
    category: "Repair services",
    primaryKeyword: "mechanic invoice template",
    title: "Free Mechanic Invoice Template | Repair Bill Format",
    h1: "Mechanic Invoice Template for Vehicle Repairs",
    billingModel: "Diagnosis + labour + spare parts",
    sampleBusiness: "RoadReady Auto Works",
    sampleCustomer: "Vikram Sharma",
    sampleItems: [
      { name: "Vehicle diagnosis", detail: "Engine noise and road test", amount: 700 },
      { name: "Repair labour", detail: "Brake-pad replacement", amount: 1800 },
      { name: "Brake pad set", detail: "Front wheel pair", amount: 3200 },
    ],
    required: ["Record vehicle model, registration reference, reported issue and completed repair.", "Separate diagnosis, labour, parts and consumables so the customer can verify the repair bill.", "Mention warranty for parts or labour and add GST details where applicable."],
    tips: ["Mention odometer reading when it matters.", "Show part brand or part number for expensive replacements.", "Deduct advance payments separately."],
    relatedSlugs: ["auto-repair-invoice-template", "mobile-repair-invoice-template", "computer-repair-invoice-template"],
  }),
  makeTemplate({
    slug: "auto-repair-invoice-template",
    profession: "Auto Repair",
    category: "Repair services",
    primaryKeyword: "auto repair invoice template",
    title: "Free Auto Repair Invoice Template | GST Bill PDF",
    h1: "Auto Repair Invoice Template for Garage Billing",
    billingModel: "Service package + parts + labour",
    sampleBusiness: "Prime Garage Services",
    sampleCustomer: "Nexa Fleet Logistics",
    sampleItems: [
      { name: "Periodic service", detail: "Oil, filter and inspection", amount: 2400 },
      { name: "Technician labour", detail: "Suspension check and adjustment", amount: 1800 },
      { name: "Engine oil", detail: "Synthetic oil · 4 litres", amount: 3600 },
    ],
    required: ["Add vehicle, service date, garage job card and work performed.", "List service package, labour, parts and consumables as separate bill lines.", "Add tax, payment status and warranty notes before delivering the vehicle."],
    tips: ["Reference the job card number.", "Mention customer approval for extra repairs.", "Keep consumables separate from major parts."],
    relatedSlugs: ["mechanic-invoice-template", "transport-invoice-template", "courier-invoice-template"],
  }),
  makeTemplate({
    slug: "pest-control-invoice-template",
    profession: "Pest Control",
    category: "Home services",
    primaryKeyword: "pest control invoice template",
    title: "Free Pest Control Invoice Template | Service Bill",
    h1: "Pest Control Invoice Template for Treatment Visits",
    billingModel: "Visit + treatment area + chemical service",
    sampleBusiness: "SafeNest Pest Solutions",
    sampleCustomer: "Lotus Apartments Association",
    sampleItems: [
      { name: "Site inspection", detail: "Kitchen and common areas", amount: 800 },
      { name: "Cockroach treatment", detail: "Gel and spray service", amount: 3200 },
      { name: "Follow-up visit", detail: "One scheduled recheck", amount: 900 },
    ],
    required: ["Mention treated property, pest type, service date and covered areas.", "Show visit charge, treatment package, area size or number of rooms.", "State safety instructions, service warranty and tax details clearly."],
    tips: ["Include warranty period for repeat treatment.", "Add apartment or floor details for societies.", "Mention whether chemicals and follow-up are included."],
    relatedSlugs: ["cleaning-service-invoice-template", "plumber-invoice-template", "maintenance-invoice-template"],
  }),
  makeTemplate({
    slug: "interior-designer-invoice-template",
    profession: "Interior Designer",
    category: "Creative and design services",
    primaryKeyword: "interior designer invoice template",
    title: "Free Interior Designer Invoice Template | GST PDF",
    h1: "Interior Designer Invoice Template for Design Projects",
    billingModel: "Design fee + milestone + procurement",
    sampleBusiness: "Studio Niva Interiors",
    sampleCustomer: "Rohan Mehta",
    sampleItems: [
      { name: "Concept design", detail: "Living room and bedroom", amount: 25000 },
      { name: "3D visualisation", detail: "Four rendered views", amount: 18000 },
      { name: "Site coordination", detail: "Two site visits", amount: 7000 },
    ],
    required: ["Name the project, room scope, design phase and approval reference.", "Separate design fee, site visits, procurement fee and vendor reimbursements.", "Add milestone due date, tax treatment and accepted payment mode."],
    tips: ["Invoice design and execution separately.", "Reference the signed proposal.", "Show advances and balance clearly."],
    relatedSlugs: ["architect-invoice-template", "contractor-invoice-template", "carpenter-invoice-template"],
  }),
  makeTemplate({
    slug: "architect-invoice-template",
    profession: "Architect",
    category: "Professional services",
    primaryKeyword: "architect invoice template",
    title: "Free Architect Invoice Template | Design Fee Bill",
    h1: "Architect Invoice Template for Design and Site Work",
    billingModel: "Design stage + drawings + site visits",
    sampleBusiness: "LineForm Architects",
    sampleCustomer: "UrbanNest Developers",
    sampleItems: [
      { name: "Schematic design", detail: "Concept drawings", amount: 45000 },
      { name: "Working drawings", detail: "Structural coordination set", amount: 65000 },
      { name: "Site visit", detail: "Progress review", amount: 8000 },
    ],
    required: ["Add project name, plot/site address, design stage and drawing reference.", "List design fees, drawings, approvals, site visits and reimbursable expenses separately.", "Mention billing milestone, tax details and payment terms from the agreement."],
    tips: ["Connect each invoice to a design phase.", "Separate statutory fees from professional fees.", "Use the client's legal entity name."],
    relatedSlugs: ["interior-designer-invoice-template", "contractor-invoice-template", "consultant-invoice-template"],
  }),
  makeTemplate({
    slug: "tutor-invoice-template",
    profession: "Tutor",
    category: "Education services",
    primaryKeyword: "tutor invoice template",
    title: "Free Tutor Invoice Template | Tuition Fee Bill",
    h1: "Tutor Invoice Template for Classes and Sessions",
    billingModel: "Session, hourly or monthly tuition",
    sampleBusiness: "BrightPath Tutoring",
    sampleCustomer: "Parent of Aarav Gupta",
    sampleItems: [
      { name: "Math tuition", detail: "8 sessions · Grade 10", amount: 8000 },
      { name: "Practice test review", detail: "Two review classes", amount: 1800 },
      { name: "Study material", detail: "Printed worksheets", amount: 700 },
    ],
    required: ["Add student name, subject, class level, session dates and tutor details.", "Show hourly rate, session count, monthly fee or package pricing.", "Mention due date, paid amount and tax details when applicable."],
    tips: ["State the month covered.", "Separate study materials from tuition.", "Show missed or extra sessions clearly."],
    relatedSlugs: ["coaching-invoice-template", "consultant-invoice-template", "freelancer-invoice-template"],
  }),
  makeTemplate({
    slug: "coaching-invoice-template",
    profession: "Coaching Institute",
    category: "Education services",
    primaryKeyword: "coaching invoice template",
    title: "Free Coaching Invoice Template | Fee Receipt PDF",
    h1: "Coaching Invoice Template for Course Fees",
    billingModel: "Course fee + instalment + material",
    sampleBusiness: "AchieveMore Coaching Centre",
    sampleCustomer: "Sneha Iyer",
    sampleItems: [
      { name: "JEE foundation batch", detail: "July 2026 instalment", amount: 18000 },
      { name: "Test series", detail: "Monthly assessment pack", amount: 2500 },
      { name: "Course material", detail: "Printed modules", amount: 1800 },
    ],
    required: ["Mention student, course, batch, instalment period and receipt reference.", "Break out course fee, test series, books and discounts.", "Add payment mode, balance due and tax details where required."],
    tips: ["Show instalment number.", "Mention batch or course code.", "Keep scholarship discounts visible."],
    relatedSlugs: ["tutor-invoice-template", "gym-invoice-template", "consultant-invoice-template"],
    searchIntents: ["coaching invoice template", "coaching fee receipt", "coaching bill format", "tuition fee invoice", "course fee receipt"],
  }),
  makeTemplate({
    slug: "event-planner-invoice-template",
    profession: "Event Planner",
    category: "Events and hospitality",
    primaryKeyword: "event planner invoice template",
    title: "Free Event Planner Invoice Template | GST Bill",
    h1: "Event Planner Invoice Template for Event Services",
    billingModel: "Planning fee + vendors + event day charges",
    sampleBusiness: "Mosaic Events Co.",
    sampleCustomer: "Aarohi Enterprises",
    sampleItems: [
      { name: "Event planning fee", detail: "Corporate launch event", amount: 35000 },
      { name: "Vendor coordination", detail: "Stage, lights and sound", amount: 22000 },
      { name: "Event-day supervision", detail: "Two coordinators", amount: 12000 },
    ],
    required: ["Add event name, venue, date, package and approved scope.", "Separate planning fee, vendor pass-throughs, rentals and day-of coordination.", "Show deposit received, balance due, tax and cancellation terms."],
    tips: ["Mention event date prominently.", "Deduct deposits clearly.", "Separate reimbursable vendor costs."],
    relatedSlugs: ["catering-invoice-template", "wedding-photographer-invoice-template", "photographer-invoice-template"],
  }),
  makeTemplate({
    slug: "wedding-photographer-invoice-template",
    profession: "Wedding Photographer",
    category: "Creative services",
    primaryKeyword: "wedding photographer invoice template",
    title: "Free Wedding Photographer Invoice Template | PDF",
    h1: "Wedding Photographer Invoice Template for Packages",
    billingModel: "Package + add-ons + album",
    sampleBusiness: "Vows & Frames Studio",
    sampleCustomer: "Ananya and Kabir",
    sampleItems: [
      { name: "Wedding coverage", detail: "Two-day package", amount: 85000 },
      { name: "Candid photographer", detail: "Additional shooter", amount: 25000 },
      { name: "Photo album", detail: "Premium 40-page album", amount: 18000 },
    ],
    required: ["Mention event dates, venues, package, deliverables and client names.", "Break out coverage, extra shooters, editing, travel and album charges.", "Show booking advance, remaining balance, GST and due date."],
    tips: ["List each event date.", "Show advance received.", "Mention delivery timeline or album add-ons."],
    relatedSlugs: ["photographer-invoice-template", "event-planner-invoice-template", "makeup-artist-invoice-template"],
  }),
  makeTemplate({
    slug: "catering-invoice-template",
    profession: "Catering",
    category: "Events and hospitality",
    primaryKeyword: "catering invoice template",
    title: "Free Catering Invoice Template | Food Bill PDF",
    h1: "Catering Invoice Template for Food and Events",
    billingModel: "Per plate + service + rentals",
    sampleBusiness: "TastyTrail Caterers",
    sampleCustomer: "Sundar Banquet Hall",
    sampleItems: [
      { name: "Vegetarian buffet", detail: "120 plates", amount: 54000 },
      { name: "Service staff", detail: "Six servers", amount: 7200 },
      { name: "Serving counters", detail: "Rental and setup", amount: 6500 },
    ],
    required: ["Add event date, venue, menu/package, guest count and service time.", "Show per-plate charges, staff, rentals, transport and add-ons separately.", "Mention advance received, balance due, tax and cancellation terms."],
    tips: ["Keep guest count visible.", "Separate food from rentals.", "Show wastage or extra plate approval if applicable."],
    relatedSlugs: ["restaurant-invoice-template", "event-planner-invoice-template", "hotel-invoice-template"],
  }),
  makeTemplate({
    slug: "restaurant-invoice-template",
    profession: "Restaurant",
    category: "Events and hospitality",
    primaryKeyword: "restaurant bill format",
    title: "Restaurant Bill Format & Invoice Template | Word, Excel, PDF",
    h1: "Restaurant Bill Format and Invoice Template",
    description: "Use this restaurant bill format and invoice template for food, beverage, service charge and GST billing. See Word, Excel and PDF layout guidance for restaurant bills.",
    intro: "Use this restaurant invoice format to create a clear food bill for dine-in, takeaway, delivery, cafe sales, catering and party orders. The practical template shows the fields to use whether you prepare the restaurant bill in Word, Excel or PDF.",
    billingModel: "Food items + service + tax",
    sampleBusiness: "Copper Bowl Restaurant",
    sampleCustomer: "Table 14 Guest",
    sampleItems: [
      { name: "North Indian thali", detail: "4 plates", amount: 1800 },
      { name: "Beverages", detail: "Assorted drinks", amount: 650 },
      { name: "Service charge", detail: "As displayed", amount: 245 },
    ],
    required: ["Add bill number, table/order reference, date and customer details if required.", "List food items, quantities, discounts and service charges clearly.", "Apply the correct GST breakup and show paid or due status."],
    tips: ["Mention takeaway or dine-in where useful.", "Show discounts before tax.", "Keep service charge transparent."],
    relatedSlugs: ["catering-invoice-template", "hotel-invoice-template", "salon-invoice-template"],
    searchIntents: ["restaurant invoice generator", "restaurant bill maker", "restaurant bill format", "restaurant bill template", "restaurant invoice template", "online restaurant bill maker", "restaurant bill format in word", "restaurant bill format in excel"],
    faqs: [
      ["What should a restaurant bill format include?", "A restaurant bill format should include restaurant details, bill number, table or order reference, date, itemised food and beverage charges, discounts, tax, service charges, total and payment status."],
      ["Can I use this as a restaurant bill format in Word?", "Yes. In Word, place restaurant details and bill information at the top, then use an item table for food, drinks, quantity, rate, tax and total."],
      ["Can I use this restaurant bill template in Excel?", "Yes. Excel is useful for calculating quantities, discounts, tax, service charges and final totals. Export the completed bill as PDF before sharing."],
      ["What is an online restaurant bill maker?", "An online restaurant bill maker helps create itemised food bills by adding menu items, quantities, rates, tax and customer details, then previewing the final bill."],
      ["Can I use this for takeaway and catering orders?", "Yes. Add the order type, event or delivery details, itemised menu items, quantity, charges and payment terms as needed."],
      ["Can I download a restaurant invoice PDF?", "Yes. Create and preview the invoice in InvoiceWala, then save it and download a professional PDF after signup or login."],
    ],
    updatedAt: "2026-08-08",
  }),
  makeTemplate({
    slug: "hotel-invoice-template",
    profession: "Hotel",
    category: "Events and hospitality",
    primaryKeyword: "hotel bill format",
    title: "Hotel Bill Format & Invoice Template | Word, Excel, PDF",
    h1: "Hotel Bill Format and Invoice Template for Room Bills",
    description: "Use this hotel bill format and invoice template for room stays, food, laundry and other services. See Word, Excel and PDF layout guidance for hotel invoices.",
    intro: "Use this hotel invoice format to create a clear room bill for stays, restaurant charges, laundry, minibar and other guest services. The practical template shows the fields to use whether you prepare a hotel bill in Word, Excel or PDF.",
    billingModel: "Room stay + services + tax",
    sampleBusiness: "Hotel Azure Grand",
    sampleCustomer: "Rajat Kapoor",
    sampleItems: [
      { name: "Room tariff", detail: "Deluxe room · 2 nights", amount: 9000 },
      { name: "Restaurant charges", detail: "In-room dining", amount: 1800 },
      { name: "Laundry service", detail: "Express laundry", amount: 650 },
    ],
    required: ["Mention guest name, room number, check-in/check-out dates and booking reference.", "Break out room tariff, food, laundry, minibar and other services.", "Show tax, deposit, balance due and payment mode clearly."],
    tips: ["Include stay dates in every room invoice.", "Separate food and room charges.", "Use booking ID for online reservations."],
    relatedSlugs: ["travel-agency-invoice-template", "restaurant-invoice-template", "catering-invoice-template"],
    searchIntents: ["hotel bill format", "hotel bill format in word", "hotel bill format in excel", "hotel invoice format", "hotel invoice format in word", "hotel invoice format in excel", "hotel invoice pdf", "hotel bill format pdf", "hotel room bill format", "hotel bill template word", "hotel invoice template excel"],
    faqs: [
      ["What should a hotel bill format include?", "A hotel bill format should include hotel details, guest name, room number, booking reference, check-in and check-out dates, room tariff, other service charges, tax, deposit, balance due and payment mode."],
      ["Can I use this as a hotel bill format in Word?", "Yes. Use the same structure in Word: hotel and guest details at the top, stay details and an itemised table for room, food, laundry, tax and total."],
      ["Can I use this as a hotel bill format in Excel?", "Yes. Excel is useful when you need formulas for room nights, service charges, tax, deposits and balance. Export the completed hotel invoice as PDF before sharing."],
      ["What is a hotel room bill format?", "A hotel room bill format is a hotel invoice focused on stay details such as room type, room number, check-in and check-out dates, number of nights, tariff, taxes and final payable amount."],
      ["Can I send a hotel invoice as PDF?", "Yes. PDF keeps the hotel invoice layout stable for email, WhatsApp, corporate accounts teams and guest records."],
      ["Should hotel food and laundry charges be separate?", "Yes. Separate room tariff, restaurant, laundry, minibar, transport and other charges so the guest or company can verify the final bill easily."],
    ],
    updatedAt: "2026-08-08",
  }),
  makeTemplate({
    slug: "travel-agency-invoice-template",
    profession: "Travel Agency",
    category: "Travel and logistics",
    primaryKeyword: "travel agency invoice template",
    title: "Free Travel Agency Invoice Template | Tour Bill",
    h1: "Travel Agency Invoice Template for Trips and Bookings",
    billingModel: "Package + booking + service fee",
    sampleBusiness: "TripNest Holidays",
    sampleCustomer: "Isha Menon",
    sampleItems: [
      { name: "Goa travel package", detail: "3 nights · 2 travellers", amount: 32000 },
      { name: "Flight booking support", detail: "Service fee", amount: 1500 },
      { name: "Airport transfer", detail: "Private cab", amount: 2200 },
    ],
    required: ["Add traveller names, destination, dates, booking references and package inclusions.", "Separate package, tickets, transfers, hotel and service fees.", "Mention tax, cancellation terms, advance and final payment due date."],
    tips: ["Use booking IDs for flights/hotels.", "Show inclusions and exclusions briefly.", "Deduct advances separately."],
    relatedSlugs: ["hotel-invoice-template", "transport-invoice-template", "logistics-invoice-template"],
  }),
  makeTemplate({
    slug: "logistics-invoice-template",
    profession: "Logistics",
    category: "Travel and logistics",
    primaryKeyword: "logistics invoice template",
    title: "Free Logistics Invoice Template | Freight Bill Format",
    h1: "Logistics Invoice Template for Freight Bills",
    billingModel: "Consignment + freight + handling",
    sampleBusiness: "NorthRoute Logistics",
    sampleCustomer: "Evergreen Traders",
    sampleItems: [
      { name: "Freight charges", detail: "Delhi to Jaipur · 2.5 tonnes", amount: 18500 },
      { name: "Loading and unloading", detail: "Warehouse handling", amount: 2400 },
      { name: "Waiting charge", detail: "Approved delay", amount: 1200 },
    ],
    required: ["Add LR/GR number, route, vehicle, consignment and delivery date.", "Show freight basis, handling, waiting, fuel surcharge and insurance separately.", "Add GST, e-way bill reference where needed and payment terms."],
    tips: ["Mention route and weight.", "Reference consignment number.", "Separate detention or waiting charges.", "Use logistics invoice sample lines for freight, handling, detention, insurance and fuel surcharge."],
    relatedSlugs: ["transport-invoice-template", "courier-invoice-template", "travel-agency-invoice-template"],
    searchIntents: ["logistics invoice sample", "logistics bill format", "freight invoice template", "freight bill format", "transport logistics invoice"],
  }),
  makeTemplate({
    slug: "courier-invoice-template",
    profession: "Courier",
    category: "Travel and logistics",
    primaryKeyword: "courier invoice template",
    title: "Free Courier Invoice Template & Bill Format | PDF",
    h1: "Courier Invoice Template for Delivery Bills",
    billingModel: "Shipment + weight + delivery service",
    sampleBusiness: "SwiftBox Courier",
    sampleCustomer: "UrbanCart Sellers",
    sampleItems: [
      { name: "Local deliveries", detail: "35 parcels", amount: 2800 },
      { name: "Express surcharge", detail: "Same-day deliveries", amount: 1250 },
      { name: "Packaging", detail: "Bubble mailers and labels", amount: 650 },
    ],
    required: ["Add shipment IDs, pickup/delivery locations, parcel count and service type.", "Show per-shipment rate, weight slabs, packaging and express charges.", "Mention tax, fuel surcharge, payment terms and delivery proof references."],
    tips: ["Use shipment or AWB references.", "Separate packaging and express charges.", "Mention COD remittance if applicable.", "For courier bill format searches, show parcel count, shipment ID, weight slab and delivery service level clearly."],
    relatedSlugs: ["logistics-invoice-template", "transport-invoice-template", "ecommerce-seller-invoice-template"],
    searchIntents: ["courier bill format", "courier invoice format", "delivery bill format", "parcel delivery invoice", "AWB invoice format"],
  }),
  makeTemplate({
    slug: "printing-invoice-template",
    profession: "Printing",
    category: "Business services",
    primaryKeyword: "printing invoice template",
    title: "Free Printing Invoice Template | Print Bill Format",
    h1: "Printing Invoice Template for Print Jobs",
    billingModel: "Print quantity + paper + finishing",
    sampleBusiness: "InkPoint Printers",
    sampleCustomer: "Nova Marketing LLP",
    sampleItems: [
      { name: "Brochure printing", detail: "1,000 copies · A4", amount: 8500 },
      { name: "Lamination", detail: "Gloss finish", amount: 2200 },
      { name: "Design adjustment", detail: "Pre-press correction", amount: 1200 },
    ],
    required: ["Add job name, size, paper type, colour mode and approved proof reference.", "Show quantity, per-unit price, finishing, design and delivery separately.", "Mention tax, advance, final balance and reprint terms."],
    tips: ["Reference approved artwork.", "Keep paper and finishing visible.", "Show quantity-based pricing."],
    relatedSlugs: ["advertising-invoice-template", "graphic-designer-invoice-template", "digital-marketing-agency-invoice-template"],
  }),
  makeTemplate({
    slug: "advertising-invoice-template",
    profession: "Advertising Agency",
    category: "Business services",
    primaryKeyword: "advertising invoice template",
    title: "Free Advertising Invoice Template | Agency Bill",
    h1: "Advertising Invoice Template for Campaign Billing",
    billingModel: "Creative fee + media + management",
    sampleBusiness: "BrightSignal Advertising",
    sampleCustomer: "FreshLeaf Foods",
    sampleItems: [
      { name: "Campaign creative", detail: "Static and video ad set", amount: 28000 },
      { name: "Media management fee", detail: "July 2026 campaign", amount: 12000 },
      { name: "Ad spend reimbursement", detail: "Approved media budget", amount: 50000 },
    ],
    required: ["Add campaign name, platform, period, purchase order and approved scope.", "Separate creative fee, media spend, management fee and reimbursements.", "Show GST, payment due date and supporting report reference."],
    tips: ["Separate ad spend from service fee.", "Mention campaign period.", "Attach report references for large clients."],
    relatedSlugs: ["digital-marketing-agency-invoice-template", "printing-invoice-template", "content-writer-invoice-template"],
  }),
  makeTemplate({
    slug: "security-service-invoice-template",
    profession: "Security Service",
    category: "Business services",
    primaryKeyword: "security service invoice template",
    title: "Security Guard Bill Format & Invoice Template | Free PDF",
    h1: "Security Service Invoice Template for Guard Services",
    billingModel: "Guard shift + site + monthly contract",
    sampleBusiness: "ShieldPro Security",
    sampleCustomer: "Orchid Tech Park",
    sampleItems: [
      { name: "Security guards", detail: "2 guards · 26 day shifts", amount: 52000 },
      { name: "Night supervision", detail: "Monthly supervisor visit", amount: 8000 },
      { name: "Uniform and equipment", detail: "Approved charge", amount: 3500 },
    ],
    required: ["Mention site, service period, guard count, shift type and attendance reference.", "Show monthly rate, extra shifts, supervision and equipment charges separately.", "Add GST, contract reference, deductions and payment terms."],
    tips: ["Reference attendance sheets.", "Separate extra shifts.", "Mention contract period and site name."],
    relatedSlugs: ["maintenance-invoice-template", "cleaning-service-invoice-template", "pest-control-invoice-template"],
  }),
  makeTemplate({
    slug: "maintenance-invoice-template",
    profession: "Maintenance Service",
    category: "Home services",
    primaryKeyword: "maintenance invoice template",
    title: "Free Maintenance Invoice Template | Service Bill",
    h1: "Maintenance Invoice Template for AMC and Repairs",
    billingModel: "AMC + visit + parts",
    sampleBusiness: "FixWell Maintenance Co.",
    sampleCustomer: "Pearl Residency",
    sampleItems: [
      { name: "Monthly AMC visit", detail: "Preventive maintenance", amount: 6500 },
      { name: "Repair labour", detail: "Pump room service", amount: 2200 },
      { name: "Replacement part", detail: "Pressure switch", amount: 1800 },
    ],
    required: ["Add site, AMC number, service date, asset and completed work.", "Separate included maintenance, extra labour, parts and emergency visits.", "Mention tax, service warranty and next maintenance date where useful."],
    tips: ["Reference AMC contract.", "Show included vs chargeable work.", "List asset details for societies or offices."],
    relatedSlugs: ["repair-service-invoice-template", "hvac-technician-invoice-template", "electrician-invoice-template"],
  }),
  makeTemplate({
    slug: "repair-service-invoice-template",
    profession: "Repair Service",
    category: "Repair services",
    primaryKeyword: "repair service invoice template",
    title: "Free Repair Service Invoice Template | PDF Bill",
    h1: "Repair Service Invoice Template for Labour and Parts",
    billingModel: "Inspection + repair + spare parts",
    sampleBusiness: "RapidRepair Services",
    sampleCustomer: "Kavya Nair",
    sampleItems: [
      { name: "Inspection", detail: "Fault diagnosis", amount: 500 },
      { name: "Repair labour", detail: "Technician service", amount: 1500 },
      { name: "Replacement component", detail: "Approved spare part", amount: 2300 },
    ],
    required: ["Record item/device, issue, repair date and work completed.", "Show diagnosis, labour, spare parts, pickup/delivery and discounts separately.", "Add warranty, payment status and GST details if applicable."],
    tips: ["Identify the repaired item.", "State warranty period.", "Separate service fee from spare parts."],
    relatedSlugs: ["mobile-repair-invoice-template", "computer-repair-invoice-template", "mechanic-invoice-template"],
  }),
  makeTemplate({
    slug: "software-company-invoice-template",
    profession: "Software Company",
    category: "Technology services",
    primaryKeyword: "software company invoice template",
    title: "Free Software Company Invoice Template | GST PDF",
    h1: "Software Company Invoice Template for Projects and SaaS",
    billingModel: "Milestone + licence + support",
    sampleBusiness: "CloudNest Software Pvt Ltd",
    sampleCustomer: "Rivora Retail",
    sampleItems: [
      { name: "Product development milestone", detail: "Sprint 3 delivery", amount: 95000 },
      { name: "SaaS subscription", detail: "July 2026 usage", amount: 18000 },
      { name: "Technical support", detail: "Priority support pack", amount: 12000 },
    ],
    required: ["Add project, subscription period, milestone, licence or purchase-order reference.", "Separate development, subscription, implementation, support and reimbursements.", "Mention GST, due date, bank details and usage period clearly."],
    tips: ["Use milestone references.", "State subscription period.", "Separate one-time setup from recurring fees."],
    relatedSlugs: ["it-services-invoice-template", "web-developer-invoice-template", "consultant-invoice-template"],
  }),
  makeTemplate({
    slug: "it-services-invoice-template",
    profession: "IT Services",
    category: "Technology services",
    primaryKeyword: "IT services invoice template",
    title: "Free IT Services Invoice Template | Support Bill",
    h1: "IT Services Invoice Template for Support and AMC",
    billingModel: "Support hours + AMC + hardware",
    sampleBusiness: "NetBridge IT Solutions",
    sampleCustomer: "Cedar Hospitals",
    sampleItems: [
      { name: "Monthly IT support", detail: "Helpdesk and monitoring", amount: 28000 },
      { name: "Onsite visit", detail: "Network troubleshooting", amount: 4500 },
      { name: "Router configuration", detail: "Business firewall setup", amount: 6500 },
    ],
    required: ["Mention service period, ticket IDs, supported assets and scope.", "Show support hours, AMC fee, onsite visits, hardware and licences separately.", "Add tax, SLA reference, payment terms and approval contact."],
    tips: ["Reference ticket numbers.", "Separate hardware from labour.", "State service period for retainers."],
    relatedSlugs: ["software-company-invoice-template", "computer-repair-invoice-template", "consultant-invoice-template"],
  }),
  makeTemplate({
    slug: "graphic-designer-invoice-template",
    profession: "Graphic Designer",
    category: "Creative services",
    primaryKeyword: "graphic designer invoice template",
    title: "Free Graphic Designer Invoice Template | PDF",
    h1: "Graphic Designer Invoice Template for Creative Work",
    billingModel: "Design deliverables + revisions + licence",
    sampleBusiness: "ShapeMint Design",
    sampleCustomer: "KindRoot Organics",
    sampleItems: [
      { name: "Logo design", detail: "Final logo and brand mark", amount: 22000 },
      { name: "Packaging artwork", detail: "Three label designs", amount: 18000 },
      { name: "Extra revisions", detail: "Two approved changes", amount: 4000 },
    ],
    required: ["Add project name, deliverables, file handoff and client approval reference.", "Separate design fee, revisions, rush fee, stock assets and usage licence.", "Mention tax, due date and whether source files are included."],
    tips: ["List deliverables clearly.", "Charge extra revision rounds separately.", "Mention source-file handoff if included."],
    relatedSlugs: ["web-designer-invoice-template", "printing-invoice-template", "content-writer-invoice-template"],
  }),
  makeTemplate({
    slug: "video-editor-invoice-template",
    profession: "Video Editor",
    category: "Creative services",
    primaryKeyword: "video editor invoice template",
    title: "Free Video Editor Invoice Template | Editing Bill",
    h1: "Video Editor Invoice Template for Editing Projects",
    billingModel: "Project edit + revisions + add-ons",
    sampleBusiness: "CutCraft Studio",
    sampleCustomer: "CreatorWorks Media",
    sampleItems: [
      { name: "Video editing", detail: "10-minute YouTube episode", amount: 12000 },
      { name: "Motion graphics", detail: "Intro and lower thirds", amount: 4500 },
      { name: "Revision round", detail: "Additional approved round", amount: 2500 },
    ],
    required: ["Add project title, video length, format, delivery date and revision scope.", "Show editing, colour correction, motion graphics, subtitles and extra revisions separately.", "Mention tax, payment terms and source/project file policy."],
    tips: ["State final video length.", "Separate subtitles and graphics.", "Track extra revision rounds."],
    relatedSlugs: ["graphic-designer-invoice-template", "photographer-invoice-template", "freelancer-invoice-template"],
  }),
  makeTemplate({
    slug: "makeup-artist-invoice-template",
    profession: "Makeup Artist",
    category: "Health and beauty",
    primaryKeyword: "makeup artist invoice template",
    title: "Free Makeup Artist Invoice Template | Beauty Bill",
    h1: "Makeup Artist Invoice Template for Bridal and Events",
    billingModel: "Package + travel + add-ons",
    sampleBusiness: "GlowRoom Makeup Studio",
    sampleCustomer: "Nisha Arora",
    sampleItems: [
      { name: "Bridal makeup package", detail: "Wedding day service", amount: 18000 },
      { name: "Hair styling", detail: "Bridal hairstyle", amount: 5000 },
      { name: "Travel charge", detail: "Venue visit", amount: 1500 },
    ],
    required: ["Add event date, venue, package, client name and service time.", "Separate makeup, hair, draping, travel, assistant and trial charges.", "Show booking advance, balance due, tax and cancellation terms."],
    tips: ["Mention event date and slot.", "Show booking advance.", "Separate travel and trial charges."],
    relatedSlugs: ["salon-invoice-template", "wedding-photographer-invoice-template", "boutique-invoice-template"],
  }),
  makeTemplate({
    slug: "boutique-invoice-template",
    profession: "Boutique",
    category: "Retail and fashion",
    primaryKeyword: "boutique invoice template",
    title: "Boutique Bill Format & Invoice Template | Free PDF",
    h1: "Boutique Invoice Template for Clothing and Tailoring",
    billingModel: "Garment + stitching + alteration",
    sampleBusiness: "Mira Boutique",
    sampleCustomer: "Rhea Malhotra",
    sampleItems: [
      { name: "Designer kurti", detail: "Custom stitched", amount: 3200 },
      { name: "Alteration", detail: "Sleeve and fitting changes", amount: 650 },
      { name: "Fabric", detail: "Premium cotton blend", amount: 1800 },
    ],
    required: ["Add garment type, size/measurement reference, delivery date and customer details.", "Separate fabric, stitching, alteration, embroidery and accessories.", "Mention advance, final balance, GST and return/alteration terms."],
    tips: ["Use order number for custom work.", "Separate fabric from stitching.", "Mention trial and delivery dates."],
    relatedSlugs: ["makeup-artist-invoice-template", "salon-invoice-template", "printing-invoice-template"],
  }),
  makeTemplate({
    slug: "dental-clinic-invoice-template",
    profession: "Dental Clinic",
    category: "Healthcare services",
    primaryKeyword: "dental clinic invoice template",
    title: "Free Dental Clinic Invoice Template | Treatment Bill",
    h1: "Dental Clinic Invoice Template for Treatment Billing",
    billingModel: "Consultation + procedure + material",
    sampleBusiness: "SmileCare Dental Clinic",
    sampleCustomer: "Aditya Rao",
    sampleItems: [
      { name: "Dental consultation", detail: "Oral examination", amount: 700 },
      { name: "Scaling and polishing", detail: "Full-mouth cleaning", amount: 2500 },
      { name: "Dental X-ray", detail: "Diagnostic imaging", amount: 800 },
    ],
    required: ["Add patient name, visit date, treatment, doctor and receipt reference.", "Separate consultation, procedure, materials, diagnostics and medicines.", "Mention payment status, tax applicability and follow-up date if needed."],
    tips: ["Avoid unnecessary health details.", "List treatment names clearly.", "Separate diagnostics from procedures."],
    relatedSlugs: ["medical-clinic-invoice-template", "pharmacy-invoice-template", "consultant-invoice-template"],
  }),
  makeTemplate({
    slug: "medical-clinic-invoice-template",
    profession: "Medical Clinic",
    category: "Healthcare services",
    primaryKeyword: "medical clinic invoice template",
    title: "Free Medical Clinic Invoice Template | Patient Bill",
    h1: "Medical Clinic Invoice Template for Patient Billing",
    billingModel: "Consultation + tests + procedures",
    sampleBusiness: "CareFirst Medical Clinic",
    sampleCustomer: "Meenal Shah",
    sampleItems: [
      { name: "Doctor consultation", detail: "General physician visit", amount: 900 },
      { name: "Basic procedure", detail: "Dressing and consumables", amount: 700 },
      { name: "Lab sample collection", detail: "Approved diagnostic support", amount: 500 },
    ],
    required: ["Add patient name, visit date, doctor, receipt number and service details.", "Separate consultation, procedure, consumables and diagnostic support.", "Show paid amount, balance, tax treatment and follow-up reference."],
    tips: ["Keep descriptions professional and minimal.", "Separate consultation from consumables.", "Use receipt number for patient records."],
    relatedSlugs: ["dental-clinic-invoice-template", "pharmacy-invoice-template", "chartered-accountant-invoice-template"],
  }),
  makeTemplate({
    slug: "pharmacy-invoice-template",
    profession: "Pharmacy",
    category: "Healthcare services",
    primaryKeyword: "pharmacy invoice template",
    title: "Free Pharmacy Invoice Template | Medicine Bill",
    h1: "Pharmacy Invoice Template for Medicine Bills",
    billingModel: "Medicine items + quantity + tax",
    sampleBusiness: "HealthPlus Pharmacy",
    sampleCustomer: "Walk-in Customer",
    sampleItems: [
      { name: "Prescription medicine", detail: "Tablet strip · 2 units", amount: 420 },
      { name: "Wellness product", detail: "Vitamin supplement", amount: 650 },
      { name: "Delivery charge", detail: "Local delivery", amount: 60 },
    ],
    required: ["Add bill number, customer/patient details if needed, item names and batch/expiry where required.", "Show medicine quantity, MRP, discount, tax and delivery charge separately.", "Mention payment mode, tax breakup and prescription reference when applicable."],
    tips: ["Record batch and expiry where required.", "Show discounts clearly.", "Separate delivery charges."],
    relatedSlugs: ["medical-clinic-invoice-template", "dental-clinic-invoice-template", "ecommerce-seller-invoice-template"],
  }),
  makeTemplate({
    slug: "real-estate-agent-invoice-template",
    profession: "Real Estate Agent",
    category: "Professional services",
    primaryKeyword: "real estate agent invoice template",
    title: "Free Real Estate Agent Invoice Template | Commission Bill",
    h1: "Real Estate Agent Invoice Template for Commission Fees",
    billingModel: "Commission + service fee + documentation",
    sampleBusiness: "MetroKeys Realty",
    sampleCustomer: "Apex Properties LLP",
    sampleItems: [
      { name: "Brokerage commission", detail: "Commercial lease closure", amount: 75000 },
      { name: "Documentation support", detail: "Agreement coordination", amount: 8000 },
      { name: "Site visits", detail: "Approved client visits", amount: 5000 },
    ],
    required: ["Add property reference, client/entity, deal type, agreement date and commission basis.", "Separate brokerage, documentation, site visits and reimbursable expenses.", "Mention GST, due date and any TDS or agreed deduction reference."],
    tips: ["State commission basis clearly.", "Reference property and deal type.", "Show deductions transparently."],
    relatedSlugs: ["consultant-invoice-template", "chartered-accountant-invoice-template", "architect-invoice-template"],
  }),
  makeTemplate({
    slug: "ecommerce-seller-invoice-template",
    profession: "Ecommerce Seller",
    category: "Retail and fashion",
    primaryKeyword: "ecommerce seller invoice template",
    title: "Free Ecommerce Seller Invoice Template | GST Bill",
    h1: "Ecommerce Seller Invoice Template for Online Orders",
    billingModel: "Product + shipping + discount",
    sampleBusiness: "UrbanCart Sellers",
    sampleCustomer: "Online Customer",
    sampleItems: [
      { name: "Product sale", detail: "Order #IW-1042", amount: 1499 },
      { name: "Shipping charge", detail: "Standard delivery", amount: 99 },
      { name: "Coupon discount", detail: "Festive offer", amount: -150 },
    ],
    required: ["Add order ID, customer, shipping address, SKU and product details.", "Show product price, quantity, discount, shipping and returns separately.", "Mention GST, payment mode, marketplace reference and delivery details."],
    tips: ["Use order and SKU references.", "Show discounts before final total.", "Separate shipping from product value."],
    relatedSlugs: ["courier-invoice-template", "pharmacy-invoice-template", "boutique-invoice-template"],
  }),
];
