export type SeoPage = {
  slug: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  intent: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  sections: Array<{ title: string; body: string }>;
  faqs: Array<[string, string]>;
  cta: string;
  ctaHref: string;
  internalLinks: Array<{ href: string; label: string }>;
  schema: Array<"FAQPage" | "SoftwareApplication" | "BreadcrumbList" | "HowTo">;
  educationBlocks?: Array<{ title: string; body: string }>;
  comparisons?: Array<{ title: string; invoiceWala: string; alternative: string }>;
};

const defaultLinks = [
  { href: "/free-invoice", label: "Create a free invoice" },
  { href: "/pricing", label: "View ₹199 Pro pricing" },
  { href: "/tools/gst-calculator", label: "GST calculator" },
  { href: "/invoice-number-generator", label: "Invoice number generator" },
];

export const seoPages: SeoPage[] = [
  {
    slug: "free-invoice-generator",
    primaryKeyword: "free invoice generator",
    secondaryKeywords: ["invoice maker free", "online invoice generator", "invoice PDF generator"],
    intent: "Create a free invoice online and preview it before signup.",
    title: "Free Invoice Generator India | Create PDF Invoices Online",
    description: "Create a professional invoice online for free. Add client details, items, tax, discounts and preview your PDF before signup with InvoiceWala.",
    h1: "Free Invoice Generator",
    intro: "Create a clean invoice for freelance work, sales, repairs, consulting or services in a few simple steps.",
    sections: [
      { title: "Create invoices before signup", body: "Add your business name, customer details, line items, taxes and payment terms first. Signup is only needed when you want to save and download the PDF." },
      { title: "Built for everyday billing", body: "Use InvoiceWala for service invoices, product sales, local jobs, consulting fees and simple business billing." },
      { title: "From invoice to payment tracking", body: "After signup, your invoice is attached to your account so you can download, edit, send reminders and track payment status." },
    ],
    educationBlocks: [
      { title: "What is an invoice?", body: "An invoice is a document you send to a customer to request payment for products or services. It usually includes your business details, customer details, invoice number, date, items, tax, total amount and payment terms." },
      { title: "Who needs invoices?", body: "Freelancers, contractors, agencies, consultants, local shops, service providers and GST businesses use invoices to bill customers professionally and keep payment records organized." },
      { title: "How to create an invoice", body: "Enter your business name, add customer details, list products or services, add quantity and rate, apply GST or tax if needed, check the total, then save and download the invoice PDF." },
      { title: "Invoice format India", body: "A practical Indian invoice format includes seller details, buyer details, invoice number, issue date, due date, line items, taxable value, GST/VAT details if applicable, total amount, notes and payment terms." },
    ],
    faqs: [
      ["Is this invoice generator free?", "Yes. You can create and preview an invoice for free. Download and saving require a free account."],
      ["Can I add tax and discounts?", "Yes. You can add quantity, rate, tax percentage and discount percentage for each item."],
      ["Can I download a PDF?", "Yes, after signup or login the invoice is saved to your account and PDF download is unlocked."],
    ],
    cta: "Create free invoice",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "invoicewala-vs-excel",
    primaryKeyword: "invoice generator better than Excel",
    secondaryKeywords: ["Excel invoice alternative", "Excel vs invoice generator", "invoice maker vs spreadsheet"],
    intent: "Compare online invoice generation with Excel invoice templates.",
    title: "InvoiceWala vs Excel | Better Way to Create Invoices",
    description: "Compare InvoiceWala and Excel for invoices. See why freelancers and small businesses use a dedicated invoice generator for PDFs, GST and payment tracking.",
    h1: "InvoiceWala vs Excel for Invoices",
    intro: "Excel is flexible, but creating, tracking and downloading invoices manually can become messy as your business grows.",
    sections: [
      { title: "Excel works until tracking breaks", body: "Spreadsheets are fine for one-off invoice templates, but invoice numbers, client history, payment status and reminders quickly become manual work." },
      { title: "InvoiceWala is built for billing", body: "InvoiceWala focuses on invoice creation, GST-ready fields, PDF export, payment status and reminders instead of generic spreadsheet editing." },
      { title: "Best for first invoices and repeat billing", body: "Create a free invoice first, then save it to your account when you want PDF download and tracking." },
    ],
    comparisons: [
      { title: "PDF creation", invoiceWala: "Built-in PDF invoice flow after signup.", alternative: "Excel often needs manual export and formatting checks." },
      { title: "Payment tracking", invoiceWala: "Statuses like draft, sent, paid and overdue.", alternative: "Manual columns and formulas." },
      { title: "GST-ready fields", invoiceWala: "Invoice fields are designed for tax-ready billing.", alternative: "Template depends on what you build yourself." },
    ],
    faqs: [
      ["Is Excel bad for invoices?", "No. Excel is useful for simple templates, but a dedicated invoice generator is easier when you need PDF export, payment tracking and repeated billing."],
      ["Can I replace Excel with InvoiceWala?", "For invoice creation and tracking, yes. You may still export data when needed."],
      ["Is InvoiceWala free to try?", "Yes. You can create and preview an invoice before signup."],
    ],
    cta: "Try InvoiceWala free",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList"],
  },
  {
    slug: "invoicewala-vs-zoho",
    primaryKeyword: "Zoho invoice alternative",
    secondaryKeywords: ["Zoho alternative for freelancers", "Zoho vs InvoiceWala", "simple invoice generator India"],
    intent: "Compare InvoiceWala with Zoho for simple invoice creation.",
    title: "InvoiceWala vs Zoho | Simple Invoice Generator for Small Businesses",
    description: "Compare InvoiceWala and Zoho for freelancers and small businesses that want fast invoices, GST-ready PDFs and simple payment tracking.",
    h1: "InvoiceWala vs Zoho for Freelancers",
    intro: "Zoho is powerful, but many freelancers and small businesses want a simpler invoice-first flow without feeling like they are setting up a large business suite.",
    sections: [
      { title: "Choose simplicity first", body: "InvoiceWala is positioned around creating invoices fast, previewing PDFs and tracking payments without a heavy setup journey." },
      { title: "GST and Indian small business focus", body: "InvoiceWala keeps language and flows focused on Indian freelancers, contractors, agencies, local shops and GST businesses." },
      { title: "Early-stage pricing", body: "Pro is priced at ₹199/month during early access so small users can adopt it without a high commitment." },
    ],
    comparisons: [
      { title: "Setup", invoiceWala: "Create invoice first, signup when saving/downloading.", alternative: "Zoho can feel broader and setup-heavy for simple users." },
      { title: "Positioning", invoiceWala: "Invoice-first with optional AI and bookkeeping.", alternative: "Larger business software ecosystem." },
      { title: "Pricing feel", invoiceWala: "₹199/month early access Pro.", alternative: "May feel more than needed for early users depending on needs." },
    ],
    faqs: [
      ["Is InvoiceWala a full Zoho replacement?", "No. InvoiceWala is simpler and invoice-first. It is best if you want fast invoices, PDFs and basic business tracking."],
      ["Who should use InvoiceWala instead?", "Freelancers, contractors, local shops and small teams that want less setup and faster invoicing."],
      ["Can I try before signup?", "Yes. Create and preview a free invoice first."],
    ],
    cta: "Create free invoice",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList"],
  },
  {
    slug: "invoicewala-vs-vyapar",
    primaryKeyword: "Vyapar alternative",
    secondaryKeywords: ["Vyapar vs InvoiceWala", "Vyapar alternative for freelancers", "simple GST invoice generator"],
    intent: "Compare InvoiceWala with Vyapar for simple GST invoicing.",
    title: "InvoiceWala vs Vyapar | Simple GST Invoice Alternative",
    description: "Compare InvoiceWala and Vyapar for users who want simple GST invoice creation, PDF previews, payment tracking and AI import options.",
    h1: "InvoiceWala vs Vyapar",
    intro: "Vyapar is known for business billing, while InvoiceWala focuses on a lightweight web-first invoice flow for freelancers, contractors, agencies and small businesses.",
    sections: [
      { title: "Web-first invoice creation", body: "InvoiceWala lets users create and preview invoices in the browser before signup, which is useful for quick conversion and first-time users." },
      { title: "Simple funnel for new users", body: "The flow is create invoice, preview, signup, download PDF and track payment. No complex accounting setup required." },
      { title: "AI import as a later advantage", body: "Bill, receipt and PDF extraction can help users turn vendor paperwork into structured records after trust is built." },
    ],
    comparisons: [
      { title: "First invoice experience", invoiceWala: "Preview before signup.", alternative: "Vyapar may fit users who want broader billing/accounting app workflows." },
      { title: "Audience", invoiceWala: "Freelancers, contractors, agencies, shops and small GST businesses.", alternative: "Broader business billing and inventory audience." },
      { title: "AI import", invoiceWala: "Positioned as an advanced automation layer.", alternative: "Feature availability depends on plan and workflow." },
    ],
    faqs: [
      ["Is InvoiceWala better than Vyapar?", "It depends. InvoiceWala is better for users who want a lightweight invoice-first web flow. Vyapar may suit broader billing and inventory needs."],
      ["Does InvoiceWala support GST invoices?", "Yes. InvoiceWala supports GST/VAT fields and GST-focused invoice pages."],
      ["Can I create an invoice without signup?", "Yes. You can preview first and sign up only when saving/downloading."],
    ],
    cta: "Try InvoiceWala",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList"],
  },
  {
    slug: "gst-invoice-generator",
    primaryKeyword: "GST invoice generator",
    secondaryKeywords: ["GST invoice maker", "GST bill generator", "tax invoice generator India"],
    intent: "Create GST-ready invoices for Indian businesses.",
    title: "GST Invoice Generator India | Create GST-Ready PDFs",
    description: "Create GST-ready invoices with client details, item rows, tax fields, PDF export and payment tracking. Built for Indian freelancers and businesses.",
    h1: "GST Invoice Generator India",
    intro: "Make GST-ready invoices with business details, customer information, tax fields and clean PDF layouts.",
    sections: [
      { title: "GST-ready invoice details", body: "Add GST/VAT IDs, item rows, taxable values, tax percentage, discounts, due dates, notes and terms." },
      { title: "For freelancers and small businesses", body: "InvoiceWala keeps GST invoice creation simple for service providers, shops, agencies, consultants and contractors." },
      { title: "Track payment after sending", body: "Save invoices to your workspace, mark them paid, and follow up when payments are pending or overdue." },
    ],
    faqs: [
      ["Can I create GST invoices in InvoiceWala?", "Yes. InvoiceWala supports GST/VAT fields and GST-focused invoice templates."],
      ["Can I add CGST, SGST or IGST?", "GST-specific reporting and layouts are supported in the product roadmap and template system."],
      ["Is this useful for non-GST businesses?", "Yes. You can also create simple invoices without GST details."],
    ],
    cta: "Create GST invoice",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "invoice-template-india",
    primaryKeyword: "invoice template India",
    secondaryKeywords: ["GST invoice format", "invoice format India", "tax invoice template"],
    intent: "Find a practical invoice format for Indian businesses.",
    title: "Invoice Template India | GST-Ready Invoice Format",
    description: "Use a simple Indian invoice template with business details, customer details, item rows, tax, totals, notes and payment terms.",
    h1: "Invoice Template India",
    intro: "Use a clear invoice format that works for freelance services, agencies, contractors and small business sales.",
    sections: [
      { title: "What an invoice should include", body: "A good invoice includes your business name, customer details, invoice date, due date, items, quantity, rate, tax, discount, total and payment terms." },
      { title: "GST-ready when needed", body: "Add GST/VAT IDs and tax fields when you need a GST-ready invoice. Keep it simple when GST is not required." },
      { title: "Use the template online", body: "Instead of editing a Word or Excel file, create the invoice online and save it as a professional PDF." },
    ],
    faqs: [
      ["Can I use this template for services?", "Yes. It works for consulting, design, development, repairs, construction and other services."],
      ["Can I use it for product sales?", "Yes. Add multiple product rows with quantity, rate and tax."],
      ["Is this a downloadable template?", "InvoiceWala lets you fill the template online and download the PDF after signup."],
    ],
    cta: "Use invoice template",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "freelancer-invoice-generator",
    primaryKeyword: "freelancer invoice generator",
    secondaryKeywords: ["freelance invoice India", "freelance bill format", "freelancer invoice template"],
    intent: "Create an invoice for freelance work.",
    title: "Freelancer Invoice Generator | Create Client Invoices Fast",
    description: "Create freelance invoices for design, development, writing, consulting and services. Preview free and save PDF invoices with InvoiceWala.",
    h1: "Freelancer Invoice Generator",
    intro: "Finished a project or monthly retainer? Create a professional invoice your client can understand quickly.",
    sections: [
      { title: "Made for client work", body: "Add project work, hourly services, retainers, milestones, taxes, discounts and notes in a simple invoice flow." },
      { title: "Send cleaner invoices", body: "A clear PDF invoice helps clients process payment faster than casual WhatsApp messages or messy spreadsheets." },
      { title: "Track payment status", body: "After saving, mark invoices as draft, sent, paid or overdue and follow up when needed." },
    ],
    faqs: [
      ["Can freelancers use InvoiceWala free?", "Yes. You can create and preview invoices free, then sign up to save and download PDFs."],
      ["Can I add GST?", "Yes. Add GST/VAT details when your freelance business requires it."],
      ["Can I reuse client details?", "Yes. After signup, save clients and reuse details for future invoices."],
    ],
    cta: "Create freelancer invoice",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "contractor-invoice-generator",
    primaryKeyword: "contractor invoice generator",
    secondaryKeywords: ["construction invoice", "contractor bill format", "service contractor invoice"],
    intent: "Create invoices for contractor work and milestones.",
    title: "Contractor Invoice Generator | Simple Contractor Bills",
    description: "Create contractor invoices for labor, materials, milestones and services. Preview invoices free and save PDFs after signup.",
    h1: "Contractor Invoice Generator",
    intro: "Create invoices for labor, materials, milestones and service work without complicated accounting software.",
    sections: [
      { title: "Bill by work completed", body: "Use item rows for labor, material, site visits, repair work, project milestones or recurring contractor services." },
      { title: "Clear totals for customers", body: "Show quantity, rate, tax, discounts and total due in a format customers can trust." },
      { title: "Follow up on pending payments", body: "Save invoices, track payment status and send reminders when work has been completed but payment is pending." },
    ],
    faqs: [
      ["Can I create construction invoices?", "Yes. Use item rows for materials, labor and milestones."],
      ["Can I add tax?", "Yes. Add GST/VAT or any tax percentage per line item."],
      ["Can I send the invoice on WhatsApp?", "Yes. Saved invoices can be shared through direct WhatsApp links."],
    ],
    cta: "Create contractor invoice",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "quotation-maker",
    primaryKeyword: "quotation maker",
    secondaryKeywords: ["quote maker", "estimate maker", "quotation format"],
    intent: "Prepare a quotation before billing.",
    title: "Free Quotation Maker | Create Professional Quotes",
    description: "Create clear quotations for services, projects, products and contractor work. Turn quotes into invoices as your workflow grows.",
    h1: "Free Quotation Maker",
    intro: "Send a clear quote before work starts so your customer understands pricing, scope and taxes.",
    sections: [
      { title: "Quote before billing", body: "Use a quotation to share expected pricing before converting approved work into an invoice." },
      { title: "Useful for services and products", body: "Create quotes for agencies, freelancers, contractors, manufacturers, shops and consultants." },
      { title: "Keep the next step simple", body: "InvoiceWala keeps invoice creation ready when the customer accepts your quotation." },
    ],
    faqs: [
      ["Is a quotation the same as an invoice?", "No. A quotation is shared before work or sale approval. An invoice requests payment after work or sale."],
      ["Can I create estimates too?", "Yes. The same structure works for estimates and quotes."],
      ["Can I convert a quote to invoice?", "This workflow is planned as part of InvoiceWala's finance document system."],
    ],
    cta: "Create quote-style invoice",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "purchase-order-generator",
    primaryKeyword: "purchase order generator",
    secondaryKeywords: ["PO generator", "purchase order format", "purchase order maker"],
    intent: "Create purchase order documents.",
    title: "Purchase Order Generator | Create PO Documents Online",
    description: "Create purchase order-style documents for vendors, products and services. Use InvoiceWala to manage invoices, purchases and expenses.",
    h1: "Purchase Order Generator",
    intro: "Prepare clear purchase order details for vendor work, product orders or service procurement.",
    sections: [
      { title: "Organize vendor purchases", body: "Use purchase order details to clarify what is being ordered, quantities, rates, taxes and expected totals." },
      { title: "Connect purchases to expenses", body: "InvoiceWala also supports purchase and expense tracking so vendor paperwork can become useful business records." },
      { title: "Simple first, automation later", body: "Start with clear document creation and add AI bill import when you need faster record keeping." },
    ],
    faqs: [
      ["What is a purchase order?", "A purchase order tells a vendor what you want to buy, quantities, rates and terms before billing."],
      ["Can InvoiceWala track purchases?", "Yes. Purchase and expense tracking are part of the product capabilities."],
      ["Can AI read vendor bills?", "InvoiceWala can parse uploaded bills and receipts into structured records after review."],
    ],
    cta: "Create business document",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "BreadcrumbList"],
  },
  {
    slug: "gst-calculator",
    primaryKeyword: "GST calculator India",
    secondaryKeywords: ["calculate GST", "GST inclusive calculator", "GST exclusive calculator"],
    intent: "Calculate GST before invoicing.",
    title: "GST Calculator India | Calculate GST Amount Online",
    description: "Calculate GST inclusive and exclusive amounts, then create a GST-ready invoice using InvoiceWala.",
    h1: "GST Calculator India",
    intro: "Calculate GST before you create the invoice so your item totals and tax values are easier to check.",
    sections: [
      { title: "Calculate before billing", body: "Use GST calculations to confirm taxable value, tax amount and total before sending an invoice." },
      { title: "Move from calculator to invoice", body: "After calculating GST, create a GST-ready invoice with item rows, due date and customer details." },
      { title: "Useful for Indian businesses", body: "Freelancers, shops, contractors and agencies can use the GST calculator before billing clients." },
    ],
    faqs: [
      ["Can I calculate inclusive GST?", "Yes. Use the GST calculator tool to work with inclusive and exclusive GST amounts."],
      ["Can I create an invoice after calculation?", "Yes. Use the free invoice maker and add the calculated tax values."],
      ["Is GST calculator free?", "Yes. The public GST calculator is free to use."],
    ],
    cta: "Open GST calculator",
    ctaHref: "/tools/gst-calculator",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "profit-margin-calculator",
    primaryKeyword: "profit margin calculator",
    secondaryKeywords: ["profit calculator", "margin calculator", "pricing calculator"],
    intent: "Calculate margin before pricing products/services.",
    title: "Profit Margin Calculator | Price Work and Products Better",
    description: "Calculate profit margin, markup and pricing before creating invoices. Free business calculator from InvoiceWala.",
    h1: "Profit Margin Calculator",
    intro: "Check your margin before you quote, sell or invoice so your business does not undercharge.",
    sections: [
      { title: "Price with confidence", body: "Use profit and margin calculations to understand cost, selling price and expected profit." },
      { title: "Useful before invoicing", body: "Once pricing is clear, create an invoice with the same rates and tax values." },
      { title: "For products and services", body: "Works for local shops, consultants, contractors, agencies and freelancers." },
    ],
    faqs: [
      ["What is profit margin?", "Profit margin shows how much profit remains after costs as a percentage of selling price."],
      ["Can I use this for service pricing?", "Yes. Use your delivery cost, time cost or vendor cost as the base."],
      ["Can I turn pricing into an invoice?", "Yes. Use InvoiceWala's free invoice creator after calculating pricing."],
    ],
    cta: "Calculate profit margin",
    ctaHref: "/tools/margin-calculator",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "invoice-number-generator",
    primaryKeyword: "invoice number generator",
    secondaryKeywords: ["invoice numbering", "invoice number format", "invoice series"],
    intent: "Generate or understand invoice numbers.",
    title: "Invoice Number Generator | Create Invoice Number Formats",
    description: "Generate clean invoice numbers and learn common invoice numbering formats before creating invoices online.",
    h1: "Invoice Number Generator",
    intro: "Use consistent invoice numbers so your billing records are easier to search, track and explain.",
    sections: [
      { title: "Why numbering matters", body: "Clear invoice numbers help you find records, avoid duplicates and keep customer communication professional." },
      { title: "Common formats", body: "Use formats like INV-0001, FY26-001 or CLIENT-001 depending on your business workflow." },
      { title: "Automatic numbering after signup", body: "InvoiceWala can generate invoice numbers automatically when invoices are saved to your workspace." },
    ],
    faqs: [
      ["Can InvoiceWala auto-generate invoice numbers?", "Yes. Saved invoices can use automatic invoice number generation."],
      ["Can I edit the invoice number?", "Yes. You can choose your own invoice number when needed."],
      ["What is a good format?", "Simple formats like INV-0001 or FY26-0001 are easy for small businesses to manage."],
    ],
    cta: "Generate invoice number",
    ctaHref: "/tools/invoice-number-generator",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "BreadcrumbList", "HowTo"],
  },
  {
    slug: "receipt-to-expense-converter",
    primaryKeyword: "receipt to expense converter",
    secondaryKeywords: ["receipt extraction AI", "expense from receipt", "receipt parser"],
    intent: "Convert receipt details into expense records.",
    title: "Receipt to Expense Converter | AI Receipt Extraction",
    description: "Upload or process receipts with AI to extract vendor, date, GST, items and totals into expense records after review.",
    h1: "Receipt to Expense Converter",
    intro: "Turn receipts and vendor bills into cleaner expense records without typing every field manually.",
    sections: [
      { title: "Extract receipt details", body: "AI import can detect vendor names, dates, GST/VAT, line items, subtotal, tax and total from receipt text or files." },
      { title: "Review before saving", body: "InvoiceWala is designed around editable previews, so extracted data can be corrected before becoming a record." },
      { title: "Connect expenses to reports", body: "Saved expenses help create simple profit and business reports over time." },
    ],
    faqs: [
      ["Can AI read receipts?", "InvoiceWala supports AI-style extraction workflows for bills, receipts and vendor PDFs."],
      ["Do I need to review extracted data?", "Yes. Always review AI extracted fields before saving financial records."],
      ["Can this help profit reports?", "Yes. Expense tracking supports monthly profit/loss summaries."],
    ],
    cta: "Try AI import",
    ctaHref: "/ai-import",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList"],
  },
  {
    slug: "pdf-to-invoice-ai",
    primaryKeyword: "PDF to invoice AI",
    secondaryKeywords: ["invoice OCR", "PDF invoice extractor", "AI invoice parser"],
    intent: "Extract invoice data from PDFs with AI.",
    title: "PDF to Invoice AI Extractor | Parse Vendor Bills",
    description: "Extract invoice numbers, vendors, GST, dates, line items and totals from PDFs or bill text with InvoiceWala AI import workflows.",
    h1: "PDF to Invoice AI Extractor",
    intro: "Use AI import to turn vendor PDFs, GST bills and invoice text into structured invoice, purchase or expense records.",
    sections: [
      { title: "Extract key fields", body: "Detect vendor/customer, invoice number, GST/VAT, dates, line items, subtotal, tax and total." },
      { title: "Edit before saving", body: "AI extraction should save time, not create blind trust. Review and edit fields before creating records." },
      { title: "Create records faster", body: "Use extracted data to create invoices, purchases, expenses or clients depending on the source document." },
    ],
    faqs: [
      ["Can I upload PDFs?", "AI import supports invoice and bill import workflows for PDFs and related document types."],
      ["Can it detect GST?", "The extraction flow is designed to surface GST/VAT fields when detected."],
      ["Is AI extraction perfect?", "No. Review extracted fields before saving."],
    ],
    cta: "Open AI import",
    ctaHref: "/ai-import",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList"],
  },
  {
    slug: "expense-tracker",
    primaryKeyword: "expense tracker small business",
    secondaryKeywords: ["business expense tracker", "track expenses India", "expense management"],
    intent: "Track expenses for a small business.",
    title: "Expense Tracker for Small Business | Track Costs and Profit",
    description: "Track business expenses, purchases, taxes and profit trends with InvoiceWala after your invoicing workflow is set up.",
    h1: "Expense Tracker for Small Business",
    intro: "Keep simple records of business costs so revenue, expenses and profit are easier to understand each month.",
    sections: [
      { title: "Track costs after billing", body: "InvoiceWala keeps invoicing first, then adds expense tracking when you need clearer business numbers." },
      { title: "Save vendor bills", body: "Use manual entry or AI import to organize vendor bills, receipts and purchases." },
      { title: "See profit trends", body: "Expense records support simple monthly profit/loss views for small businesses." },
    ],
    faqs: [
      ["Is this full accounting software?", "No. It is a simple invoicing and business tracking tool for small teams."],
      ["Can I track purchases?", "Yes. Purchase and expense tracking are supported."],
      ["Can I import receipts?", "Yes. AI import helps extract receipt and bill details."],
    ],
    cta: "Create invoice first",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList"],
  },
  {
    slug: "payment-reminder",
    primaryKeyword: "payment reminder invoice",
    secondaryKeywords: ["invoice reminder", "overdue invoice reminder", "payment follow up"],
    intent: "Remind clients to pay invoices.",
    title: "Invoice Payment Reminder Tool | Follow Up Faster",
    description: "Track pending and overdue invoices, then send payment reminders through InvoiceWala workflows and WhatsApp-friendly sharing.",
    h1: "Invoice Payment Reminder Tool",
    intro: "A good invoice is only useful when payment arrives. Track pending invoices and follow up without losing context.",
    sections: [
      { title: "Know what is unpaid", body: "Save invoices with payment status so paid, pending and overdue work is easier to monitor." },
      { title: "Follow up professionally", body: "Use clear reminders instead of rewriting awkward payment messages from scratch." },
      { title: "WhatsApp-friendly workflow", body: "Direct WhatsApp sharing helps Indian businesses follow up where customers already respond." },
    ],
    faqs: [
      ["Can InvoiceWala track overdue invoices?", "Yes. Invoice status includes draft, sent, paid and overdue workflows."],
      ["Can I send reminders by WhatsApp?", "InvoiceWala supports direct WhatsApp sharing links."],
      ["Do I need payment gateway setup?", "No. You can track manual payments too."],
    ],
    cta: "Create invoice and track payment",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList"],
  },
  {
    slug: "bookkeeping-for-small-business",
    primaryKeyword: "bookkeeping for small business",
    secondaryKeywords: ["simple bookkeeping", "small business records", "profit loss tracking"],
    intent: "Understand simple bookkeeping for small businesses.",
    title: "Simple Bookkeeping for Small Business | InvoiceWala",
    description: "Start with invoices, then track expenses, purchases, payments and profit reports without complex accounting software.",
    h1: "Simple Bookkeeping for Small Business",
    intro: "Bookkeeping should start with the records you already create: invoices, payments, bills, receipts and expenses.",
    sections: [
      { title: "Start with invoices", body: "InvoiceWala keeps the first step simple: create invoices fast and track payment status." },
      { title: "Add expenses when ready", body: "Record vendor bills, receipts and purchases to understand where money goes." },
      { title: "Review simple reports", body: "Use revenue, expense, GST and profit summaries to understand your business without heavy accounting complexity." },
    ],
    faqs: [
      ["Is InvoiceWala for accountants?", "It is built mainly for freelancers, contractors, agencies and small businesses, not complex accounting teams."],
      ["Can it track profit?", "Yes. Revenue and expense records support profit summaries."],
      ["Should I still talk to an accountant?", "For tax filing and compliance, yes. InvoiceWala helps organize your business records."],
    ],
    cta: "Create your first invoice",
    ctaHref: "/free-invoice",
    internalLinks: defaultLinks,
    schema: ["FAQPage", "SoftwareApplication", "BreadcrumbList"],
  },
];

export function seoPageBySlug(slug: string) {
  return seoPages.find((page) => page.slug === slug);
}
